package com.teamdev.jxbrowser.chromium.demo;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;


public class progress extends javax.swing.JFrame {

    /**
     * Creates new form progress
     */
    public progress() {
        initComponents();
        this.setTitle("Compressing");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        mainFile = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        currentFile = new javax.swing.JLabel();
        pb1 = new javax.swing.JProgressBar();
        pb1perc = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        pb2 = new javax.swing.JProgressBar();
        pb2perc = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        hide = new javax.swing.JButton();
        details = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        totalFiles = new javax.swing.JLabel();
        reminFile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        mainFile.setBounds(10, 10, 270, 20);
        jDesktopPane1.add(mainFile, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Adding");
        jLabel2.setBounds(10, 30, 50, 14);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        currentFile.setBounds(10, 50, 230, 20);
        jDesktopPane1.add(currentFile, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pb1.setBounds(10, 70, 280, 20);
        jDesktopPane1.add(pb1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pb1perc.setText("perc");
        pb1perc.setBounds(260, 50, 30, 20);
        jDesktopPane1.add(pb1perc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator1.setBounds(10, 160, 280, 10);
        jDesktopPane1.add(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setText("Total Files Processed");
        jLabel5.setBounds(10, 170, 130, 14);
        jDesktopPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pb2.setBounds(10, 190, 280, 20);
        jDesktopPane1.add(pb2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pb2perc.setText("perc");
        pb2perc.setBounds(260, 160, 30, 30);
        jDesktopPane1.add(pb2perc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator2.setBounds(10, 220, 280, 10);
        jDesktopPane1.add(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        hide.setText("Hide");
        hide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideActionPerformed(evt);
            }
        });
        hide.setBounds(10, 240, 130, 23);
        jDesktopPane1.add(hide, javax.swing.JLayeredPane.DEFAULT_LAYER);

        details.setText("Details");
        details.setBounds(150, 270, 140, 23);
        jDesktopPane1.add(details, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        cancel.setBounds(10, 270, 130, 23);
        jDesktopPane1.add(cancel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pause.setText("Pause");
        pause.setBounds(150, 240, 140, 23);
        jDesktopPane1.add(pause, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator3.setBounds(10, 100, 280, 10);
        jDesktopPane1.add(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setText("Total Files");
        jLabel7.setBounds(10, 110, 120, 14);
        jDesktopPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setText("Remaining Files");
        jLabel8.setBounds(10, 140, 100, 14);
        jDesktopPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        totalFiles.setBounds(260, 100, 30, 30);
        jDesktopPane1.add(totalFiles, javax.swing.JLayeredPane.DEFAULT_LAYER);
        reminFile.setBounds(260, 130, 30, 30);
        jDesktopPane1.add(reminFile, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        WindowEvent wev = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
                Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(wev);
                Toolkit.getDefaultToolkit().beep();
    }                                      

    private void hideActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        
        this.setVisible(false);
        
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new progress().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton cancel;
    javax.swing.JLabel currentFile;
    javax.swing.JButton details;
    private javax.swing.JButton hide;
    private javax.swing.JDesktopPane jDesktopPane1;
    javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    javax.swing.JLabel mainFile;
    private javax.swing.JButton pause;
    javax.swing.JProgressBar pb1;
    javax.swing.JLabel pb1perc;
    javax.swing.JProgressBar pb2;
    javax.swing.JLabel pb2perc;
    javax.swing.JLabel reminFile;
    javax.swing.JLabel totalFiles;
    // End of variables declaration                   
}
